"""empty message

Revision ID: 199bcf261491
Revises: d9950130cfd3
Create Date: 2019-08-25 13:21:54.664587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199bcf261491'
down_revision = 'd9950130cfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step_stone', 'company',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step_stone', 'company',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
