"""empty message

Revision ID: 31c61a9cf65b
Revises: 3f533cfcfaca
Create Date: 2019-08-25 16:19:24.297547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c61a9cf65b'
down_revision = '3f533cfcfaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_stone', sa.Column('site', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_stone', 'site')
    # ### end Alembic commands ###
