"""empty message

Revision ID: 71946ba532bf
Revises: 
Create Date: 2019-08-24 20:11:56.401645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71946ba532bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_stone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=250), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('company', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_stone')
    # ### end Alembic commands ###
