"""empty message

Revision ID: 87f79ef1cd03
Revises: ffc5637e0b6b
Create Date: 2019-08-25 15:43:02.814189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f79ef1cd03'
down_revision = 'ffc5637e0b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_stone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=80), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('days_left', sa.String(length=80), nullable=True),
    sa.Column('created', sa.String(length=80), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_stone')
    # ### end Alembic commands ###
