"""empty message

Revision ID: 911accd06613
Revises: beed11f7487d
Create Date: 2019-08-25 13:42:56.325697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911accd06613'
down_revision = 'beed11f7487d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_stone', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('step_stone', 'article_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_stone', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('step_stone', 'id')
    # ### end Alembic commands ###
