"""empty message

Revision ID: beed11f7487d
Revises: 9ef692e31f67
Create Date: 2019-08-25 13:40:11.019550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beed11f7487d'
down_revision = '9ef692e31f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_stone', sa.Column('article_id', sa.Integer(), nullable=False))
    op.drop_column('step_stone', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_stone', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('step_stone', 'article_id')
    # ### end Alembic commands ###
