"""empty message

Revision ID: df83143bdadb
Revises: fc1b1dd7397e
Create Date: 2019-08-25 15:25:31.341935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df83143bdadb'
down_revision = 'fc1b1dd7397e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_stone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=80), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('days_left', sa.String(length=80), nullable=True),
    sa.Column('created', sa.String(length=80), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_stone')
    # ### end Alembic commands ###
